### ISSUE TITLE
Data life Cycle diagram

### ISSUE THREAD

**Issue by StefanGerrits2** [ReiniervanLimpt/real-time-web-1920#1]
Bij user data, voeg room property toe om bij te houden in welke room de user zit.

Bij events, als er een volgorde in zit, houd dan deze volgorde aan.
Bijvoorbeeld create game and join game zouden bovenaan kunnen staan.

De kleuren blauw en zwart zou je iets beter kunnen onderscheiden.

**Comment by ReiniervanLimpt** [comment]
volgorde en DLC aangepast!
