### ISSUE TITLE
Repo

### ISSUE THREAD

**Issue by StefanGerrits2** [ReiniervanLimpt/real-time-web-1920#2]
Voeg een beschrijving toe van je applicatie.

Live link mist nog, maar dat is voor nu nog geen probleem.

Custom events toevoegen wanneer je hier aan toe bent.

Al goed op weg met het beschrijven van je API !
Je zou hier nog kunnen laten zien welke data je binnen haalt en eventueel welke data je hiervan op gaat slaan en gaat gebruiken.

Vergeet ook niet de Installation, License, Sources etc op het laatst toe te voegen.

**Comment by ReiniervanLimpt** [comment]
Done, en thanks voor de reminder!
