### ISSUE TITLE
Rubric

### ISSUE THREAD

**Issue by StefanGerrits2** [ReiniervanLimpt/real-time-web-1920#3]
![image](https://user-images.githubusercontent.com/45566396/79850617-7c45cf80-83c4-11ea-8227-02a36de88aab.png)

1. Project
App online zetten, real-time events nog erbij zetten wanneer je kan, en iets meer informatie geven over de data van je gebruikte API.

2. Complexiteit
Volgens mij heb je genoeg complexiteit als het je lukt je concept te kunnen uitwerken. Dit punt van de Rubric zal wel goed zitten.

3. Client-server interactie.
Zover ik nu weet kan de gebruiker een room aanmaken en een game createn. Dan haalt de API infotmatie op die de gebruiker kan zien. Ik denk dat dit voldoende is. Eventueel zou je nog iets kunnen toepassen dat de gebruiker de data kan manipuleren/interacteren.

4. Data management
Dit punt zit wel snor als ik je Data life cycle zie. Je heb je gebruikers in verschillende rooms verdeeld die elk hun eigen stukje informatie krijgen. Ook houd je op de server een datamodel bij genaamd event logs.

5. Multi user support 
Door het gebruik van rooms kunnen meerdere clients verbinden met de server zonder problemen. Als dit dynamisch is gemaakt zit je op dit punt ook goed.

**Comment by ReiniervanLimpt** [comment]
1. App werkt nu online, was wel een gedoe met data pushen omdat ik riot's root ssl niet op github kan zetten...

2. concept aangepast omdat data niet was wat ik verwachtte

3. Geen room's niet aan toegekomen dit kan later toegevoegd worden als meerdere client-servers connecten!

4. thanks

5. zie punt 3...
